export const LOADING_IN_PROGRESS = 'LOADING_IN_PROGRESS';
export const LOADING_SOURCES_SUCCESS = 'LOADING_SOURCES_SUCCESS';
export const LOADING_NEWS_CONTENT_SUCCESS = 'LOADING_NEWS_CONTENT_SUCCESS';
